/**
 * OpenApi specification - Firas
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: firas.fileli@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BorrowedBookResponse model module.
 * @module model/BorrowedBookResponse
 * @version 1.0
 */
class BorrowedBookResponse {
    /**
     * Constructs a new <code>BorrowedBookResponse</code>.
     * @alias module:model/BorrowedBookResponse
     */
    constructor() { 
        
        BorrowedBookResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BorrowedBookResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BorrowedBookResponse} obj Optional instance to populate.
     * @return {module:model/BorrowedBookResponse} The populated <code>BorrowedBookResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BorrowedBookResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('authorName')) {
                obj['authorName'] = ApiClient.convertToType(data['authorName'], 'String');
            }
            if (data.hasOwnProperty('isbn')) {
                obj['isbn'] = ApiClient.convertToType(data['isbn'], 'String');
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], 'Number');
            }
            if (data.hasOwnProperty('returned')) {
                obj['returned'] = ApiClient.convertToType(data['returned'], 'Boolean');
            }
            if (data.hasOwnProperty('returnApproved')) {
                obj['returnApproved'] = ApiClient.convertToType(data['returnApproved'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BorrowedBookResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BorrowedBookResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['authorName'] && !(typeof data['authorName'] === 'string' || data['authorName'] instanceof String)) {
            throw new Error("Expected the field `authorName` to be a primitive type in the JSON string but got " + data['authorName']);
        }
        // ensure the json data is a string
        if (data['isbn'] && !(typeof data['isbn'] === 'string' || data['isbn'] instanceof String)) {
            throw new Error("Expected the field `isbn` to be a primitive type in the JSON string but got " + data['isbn']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
BorrowedBookResponse.prototype['id'] = undefined;

/**
 * @member {String} title
 */
BorrowedBookResponse.prototype['title'] = undefined;

/**
 * @member {String} authorName
 */
BorrowedBookResponse.prototype['authorName'] = undefined;

/**
 * @member {String} isbn
 */
BorrowedBookResponse.prototype['isbn'] = undefined;

/**
 * @member {Number} rate
 */
BorrowedBookResponse.prototype['rate'] = undefined;

/**
 * @member {Boolean} returned
 */
BorrowedBookResponse.prototype['returned'] = undefined;

/**
 * @member {Boolean} returnApproved
 */
BorrowedBookResponse.prototype['returnApproved'] = undefined;






export default BorrowedBookResponse;

