/**
 * OpenApi specification - Firas
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: firas.fileli@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FeedbackRequest model module.
 * @module model/FeedbackRequest
 * @version 1.0
 */
class FeedbackRequest {
    /**
     * Constructs a new <code>FeedbackRequest</code>.
     * @alias module:model/FeedbackRequest
     * @param comment {String} 
     * @param bookId {Number} 
     */
    constructor(comment, bookId) { 
        
        FeedbackRequest.initialize(this, comment, bookId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, comment, bookId) { 
        obj['comment'] = comment;
        obj['bookId'] = bookId;
    }

    /**
     * Constructs a <code>FeedbackRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FeedbackRequest} obj Optional instance to populate.
     * @return {module:model/FeedbackRequest} The populated <code>FeedbackRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FeedbackRequest();

            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('bookId')) {
                obj['bookId'] = ApiClient.convertToType(data['bookId'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FeedbackRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FeedbackRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FeedbackRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }

        return true;
    }


}

FeedbackRequest.RequiredProperties = ["comment", "bookId"];

/**
 * @member {Number} note
 */
FeedbackRequest.prototype['note'] = undefined;

/**
 * @member {String} comment
 */
FeedbackRequest.prototype['comment'] = undefined;

/**
 * @member {Number} bookId
 */
FeedbackRequest.prototype['bookId'] = undefined;






export default FeedbackRequest;

