/**
 * OpenApi specification - Firas
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: firas.fileli@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthenticationRequest from './model/AuthenticationRequest';
import AuthenticationResponse from './model/AuthenticationResponse';
import BookRequest from './model/BookRequest';
import BookResponse from './model/BookResponse';
import BorrowedBookResponse from './model/BorrowedBookResponse';
import FeedbackRequest from './model/FeedbackRequest';
import FeedbackResponse from './model/FeedbackResponse';
import PageResponseBookResponse from './model/PageResponseBookResponse';
import PageResponseBorrowedBookResponse from './model/PageResponseBorrowedBookResponse';
import PageResponseFeedbackResponse from './model/PageResponseFeedbackResponse';
import RegistrationRequest from './model/RegistrationRequest';
import AuthenticationApi from './api/AuthenticationApi';
import BookApi from './api/BookApi';
import FeedbackApi from './api/FeedbackApi';


/**
* OpenApi documentation for Spring Security.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenApiSpecificationFiras = require('index'); // See note below*.
* var xxxSvc = new OpenApiSpecificationFiras.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenApiSpecificationFiras.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenApiSpecificationFiras.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenApiSpecificationFiras.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AuthenticationRequest model constructor.
     * @property {module:model/AuthenticationRequest}
     */
    AuthenticationRequest,

    /**
     * The AuthenticationResponse model constructor.
     * @property {module:model/AuthenticationResponse}
     */
    AuthenticationResponse,

    /**
     * The BookRequest model constructor.
     * @property {module:model/BookRequest}
     */
    BookRequest,

    /**
     * The BookResponse model constructor.
     * @property {module:model/BookResponse}
     */
    BookResponse,

    /**
     * The BorrowedBookResponse model constructor.
     * @property {module:model/BorrowedBookResponse}
     */
    BorrowedBookResponse,

    /**
     * The FeedbackRequest model constructor.
     * @property {module:model/FeedbackRequest}
     */
    FeedbackRequest,

    /**
     * The FeedbackResponse model constructor.
     * @property {module:model/FeedbackResponse}
     */
    FeedbackResponse,

    /**
     * The PageResponseBookResponse model constructor.
     * @property {module:model/PageResponseBookResponse}
     */
    PageResponseBookResponse,

    /**
     * The PageResponseBorrowedBookResponse model constructor.
     * @property {module:model/PageResponseBorrowedBookResponse}
     */
    PageResponseBorrowedBookResponse,

    /**
     * The PageResponseFeedbackResponse model constructor.
     * @property {module:model/PageResponseFeedbackResponse}
     */
    PageResponseFeedbackResponse,

    /**
     * The RegistrationRequest model constructor.
     * @property {module:model/RegistrationRequest}
     */
    RegistrationRequest,

    /**
    * The AuthenticationApi service constructor.
    * @property {module:api/AuthenticationApi}
    */
    AuthenticationApi,

    /**
    * The BookApi service constructor.
    * @property {module:api/BookApi}
    */
    BookApi,

    /**
    * The FeedbackApi service constructor.
    * @property {module:api/FeedbackApi}
    */
    FeedbackApi
};
