/**
 * OpenApi specification - Firas
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: firas.fileli@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiSpecificationFiras);
  }
}(this, function(expect, OpenApiSpecificationFiras) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiSpecificationFiras.BookRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BookRequest', function() {
    it('should create an instance of BookRequest', function() {
      // uncomment below and update the code to test BookRequest
      //var instance = new OpenApiSpecificationFiras.BookRequest();
      //expect(instance).to.be.a(OpenApiSpecificationFiras.BookRequest);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenApiSpecificationFiras.BookRequest();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new OpenApiSpecificationFiras.BookRequest();
      //expect(instance).to.be();
    });

    it('should have the property authorName (base name: "authorName")', function() {
      // uncomment below and update the code to test the property authorName
      //var instance = new OpenApiSpecificationFiras.BookRequest();
      //expect(instance).to.be();
    });

    it('should have the property isbn (base name: "isbn")', function() {
      // uncomment below and update the code to test the property isbn
      //var instance = new OpenApiSpecificationFiras.BookRequest();
      //expect(instance).to.be();
    });

    it('should have the property synopsis (base name: "synopsis")', function() {
      // uncomment below and update the code to test the property synopsis
      //var instance = new OpenApiSpecificationFiras.BookRequest();
      //expect(instance).to.be();
    });

    it('should have the property shareable (base name: "shareable")', function() {
      // uncomment below and update the code to test the property shareable
      //var instance = new OpenApiSpecificationFiras.BookRequest();
      //expect(instance).to.be();
    });

  });

}));
