/**
 * OpenApi specification - Firas
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: firas.fileli@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenApiSpecificationFiras);
  }
}(this, function(expect, OpenApiSpecificationFiras) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenApiSpecificationFiras.FeedbackRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FeedbackRequest', function() {
    it('should create an instance of FeedbackRequest', function() {
      // uncomment below and update the code to test FeedbackRequest
      //var instance = new OpenApiSpecificationFiras.FeedbackRequest();
      //expect(instance).to.be.a(OpenApiSpecificationFiras.FeedbackRequest);
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instance = new OpenApiSpecificationFiras.FeedbackRequest();
      //expect(instance).to.be();
    });

    it('should have the property comment (base name: "comment")', function() {
      // uncomment below and update the code to test the property comment
      //var instance = new OpenApiSpecificationFiras.FeedbackRequest();
      //expect(instance).to.be();
    });

    it('should have the property bookId (base name: "bookId")', function() {
      // uncomment below and update the code to test the property bookId
      //var instance = new OpenApiSpecificationFiras.FeedbackRequest();
      //expect(instance).to.be();
    });

  });

}));
